### PR TITLE
[250] Minor rephrasing and failure correction.

### PR DESCRIPTION
**Pull request by 0ndorio**
- Minor rephrasing.
- Adds missing details for Diffie-Hellman.
- Adds missing details for asymmetric cryptography.

review phase: 3
level: mistake || enhancement || opinion 
type: content || phrasing || grammar or spelling || design or layout

### What is wrong?

[MUST]

### How should it be?d

[MUST]

### Resources (links)

[MAY]

### References (issues, PRs)

[MAY]

### CODE REVIEW

**Comment by lucendio** [comment]
partialy applied. one question though. what part(s) of the current (see latest version) explainantion, of asym crypto is wrong. I mean, depending on which key is used to encrypt, only the other one can be decryp the cipher. it just depends which is used for what. or am I wrong?

**Comment by 0ndorio** [comment]
Your mistake here is the assumption that this choice is always possible. In some algorithms its settled which key is the public and which key is the private one. Two short examples:

(1) In DSA (https://en.wikipedia.org/wiki/Digital_Signature_Algorithm) the range for valid secret keys is much smaller then the range of valid public keys:

- Choose an N-bit prime q.
- Choose a secret key x by some random method, where 0 < x < q.

- Choose an L-bit prime modulus p such that p − 1 is a multiple of q. 
- Calculate the public key y = g^x mod p.

(2) In elliptic curve related algorithms the typical secret key is a single scalar value and the public key is a somehow related point on the curve you choose.

**Comment by lucendio** [comment]
I am sorry, a reworked version was pushed just now (https://github.com/lucendio/pdaas_thesis/commit/fd66afc4af1173d0e4a8218596b9d5a40e3e7981), not earlier as referred to in my last comment. 
so maybe you could have another look into the changes, aspecially the ones concerning asym crypto. maybe this relaxes the restrictions you mentioned.

**Comment by lucendio** [comment]
addressed in https://github.com/lucendio/pdaas_thesis/commit/872b6c50e1d3a1175369bc7850f435adef5f140f

**Pull request closed without merging**
